### ISSUE TITLE
Remove Domain Error

### ISSUE THREAD

**Issue by ShonGee** [xBourner/status-card#5]
Using the visual editor, trying to use the toggle to remove a domain gives the following error:

Uncaught TypeError: Cannot assign to read only property 'hide' of object '#<Object>'
    at me.updateConfig (status-card.js?hacstag=87855728620:88:2151)
    at me.updateVisibility (status-card.js?hacstag=87855728620:88:2565)
    at status-card.js?hacstag=87855728620:122:141
    at me.<anonymous> (status-card.js?hacstag=87855728620:94:90)
    at se.handleEvent (status-card.js?hacstag=87855728620:2:13461)
    at n (fire_event.ts:76:8)
    at ShadowRoot.<anonymous> (ha-form.ts:211:7)
    at n (fire_event.ts:76:8)
    at HTMLElement.value (ha-selector-boolean.ts:47:5)
    at $.handleEvent (lit-html.ts:2018:29)
updateConfig @ status-card.js?hacstag=87855728620:88
updateVisibility @ status-card.js?hacstag=87855728620:88
(anonymous) @ status-card.js?hacstag=87855728620:122
(anonymous) @ status-card.js?hacstag=87855728620:94
handleEvent @ status-card.js?hacstag=87855728620:2
n @ fire_event.ts:76
(anonymous) @ ha-form.ts:211
n @ fire_event.ts:76
value @ ha-selector-boolean.ts:47
handleEvent @ lit-html.ts:2018
(anonymous) @ mwc-switch-base.ts:121

Trying to remove them in yaml works
Great tool btw! Ta.

**Comment by xBourner** [comment]
cant reproduce that. which HA version do you have installed and which browser do you use?

**Comment by xBourner** [comment]
will close this due to no response
